networks:
  laravel-tdd:
    driver: bridge

services:
  # image project
  php:
    container_name: laravel-tdd-app
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel-tdd

  # nginx
  nginx:
    container_name: laravel-tdd-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel-tdd